### ISSUE TITLE
reaching out for interactive geom

### ISSUE THREAD

**Issue by goyalyashpal** [jfbouzereau/geom#1]
hi, i am just dropping by to say hi. i just found this project via 
https://en.wikipedia.org/wiki/List_of_interactive_geometry_software#License_and_platform 
 and it seemed interesting.

**Comment by jfbouzereau** [comment]
> Le 2 nov. 2021 à 19:04, yashpalgoyal1304 ***@***.***> a écrit :
> 
> 
> hi, i am just dropping by to say hi. i just found this project via
> https://en.wikipedia.org/wiki/List_of_interactive_geometry_software#License_and_platform
> 
> and it seemed interesting.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

Hello Yashpal,

Thank you for your mail. I’m glad you find this project interesting.
I have not touched it for some time now, but I had fun developing
the idea, mainly to experiment classes in javascript, and also
to provide a decent alternative to professional softwares...

Cheers

JFB
